### ISSUE TITLE
[Need help] About the "projectionDir" parameter in export(...)'s "opt" parameter?

### ISSUE THREAD

**Issue by huskier** [CadQuery/cadquery#1721]
If we want to get a SVG export like the following perspective from the door object in the Assembly example, how do we set the "projectionDir" parameter in export(...)'s "opt" parameter? I do not really understand the parameter although we have the explanation. We've tried several values, but we could get our expected result.
 **projectionDir: Direction the camera will view the shape from.**   
![Untitled001](https://github.com/user-attachments/assets/ca7db8ae-dc56-4ddb-9159-8d2b57b88e9a)

**Comment by jmwright** [comment]
A projection direction like this should get you close.

```python
"projectionDir": (-1.0, -1.0, -0.5),
```

If I remember correctly, the standard SVG image coordinate system is right-handed, whereas we are all used to left-handed coordinates. So Y is up for SVG instead of Z being up. The projection direction mechanism is very non-intuitive for me as well, and has been around since the early days of CadQuery. There has been discussion about better ways to do the views, but nothing has ever been implemented.

You might want to have a look at the [PNG export plugin](https://github.com/jmwright/cadquery-png-plugin/blob/main/README.md) I created. It uses a set of named views and a zoom factor rather than raw camera positioning. It won't do hidden lines, but if you want the black and white look of the SVG, you can set the `color_theme` to `black_and_white`. It also does not export single Workplanes at this time because it was designed to export assemblies. You can get around that limitation by creating an assembly with the Workplane as the base object.

The plugin has only been used in one project so far, so it might have bugs that I am not aware of.

**Comment by huskier** [comment]
> "projectionDir": (-1.0, -1.0, -0.5),
It's all mirrored, left-right mirrored and up-down mirrored. Again, I tried more values, but I cannot get the correct perspective.

I am very intrested in the PNG export plugin; however, my logic is based on export Compound object, just like in #1715.
```
letters = list(text3D)
letters[0].move(z=10)
text3D = compound(letters)
#export text3D as SVG

letters = list(text3D)
letters[3].move(z=10)
text3D = compound(letters)
#export text3D as SVG
```

**Comment by huskier** [comment]
Very imppressive!

However, I've got problems when installing the cadquery-png-plugin. I am on the latest master of the CadQuery. Is the cadquery-png-plugin compatible with the latest master of the CadQuery?

INFO: pip is looking at multiple versions of nlopt to determine which version is compatible with other requirements. This could take a while.
ERROR: Cannot install cadquery-png-plugin==1.0.0 and cadquery_png_plugin because these package versions have conflicting dependencies.

The conflict is caused by:
    cadquery-png-plugin 1.0.0 depends on numpy<2
    nlopt 2.9.0 depends on numpy<3 and >=2

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

**Comment by jmwright** [comment]
@huskier

> Is the cadquery-png-plugin compatible with the latest master of the CadQuery?

Yes it is, but I merged a CadQuery setup.py change yesterday that caused a conflict with the plugin's dependencies. I had the dependencies pinned during plugin development because of my conda environment. That should be fixed now if you want to try to install again.

**Comment by jmwright** [comment]
I'm not sure what you mean by "lines are not so clear" in this context since they look fine to me. You can add an `edge_width` option to the render options to get thicker edge lines, but I'm not sure if that is what you want.

**Comment by huskier** [comment]
OK, I will try edge_width later.
Thank you for your tutorial on the cadquery-png-plugin. @jmwright

**Comment by jmwright** [comment]
@adam-urbanczyk Yes, but positioning the camera by named position and zoom factor is different than we've done before. I was not sure if that would work for the broader community. I should also probably generalize the code to convert Workplanes to VTK objects directly instead of having to wrap them in an Assembly.
