### ISSUE TITLE
Exporters cleanup

### ISSUE THREAD

**Issue by adam-urbanczyk** [CadQuery/cadquery#216]
Current public exporting interface is so-so. It would be at least good to expose `exportStep` in the fluent API.

Related to #212

**Comment by marcus7070** [comment]
I'd get some use out of the AMF export option https://github.com/CadQuery/cadquery/blob/e69b2f83bde43ad6a0159a72bc058165e684e72e/cadquery/occ_impl/exporters.py#L148

The AMF format is really suited to 3D printers with dual printing heads, since it can have two (or more) objects within one file. AMF is well supported in the main open source 3D printing slicer, Slic3r. 

I haven't tried the AMF export implementation in CadQuery yet, just wanted to let you know my use case.

**Comment by jmwright** [comment]
#246 is another related issue for the exporters

**Comment by jmwright** [comment]
@adam-urbanczyk Hasn't this issue already been addressed by #415 and related issues?

**Comment by adam-urbanczyk** [comment]
Actually it did. You can export AMF using `cq.exporters.export`

**Comment by jmwright** [comment]
Ok, closing.
